implement hold space to drag the canvas
ild-games/duckling-legacy pull request #118
Opened 2016-09-12 02:11 UTC by tlein

Resolves #100

2016-09-12 02:26 UTC, tlein commented
This broke copy + paste

2016-09-17 19:34 UTC, jeffswenson requested changes
You should create a wrapper tool that is in charge of tracking the state.

2016-09-18 03:05 UTC, JeffSwenson commented on src/duckling/canvas/canvas.component.ts
> +    private _createCanvasKeyEvent(event : KeyboardEvent) : CanvasKeyEvent {
You can delete this.

2016-09-18 03:08 UTC, jeffswenson requested changes

2016-09-18 03:14 UTC, merged