Added selection box to indicate what Entity is selected on the canvas
ild-games/duckling-legacy pull request #123
Opened 2016-09-15 02:36 UTC by jimmcnulty41

2016-09-17 16:11 UTC, tlein commented on src/duckling/canvas/map-editor.component.ts
> +    private buildSelectionBox() : DisplayObject {
Privates need to be preceded with an underscore

2016-09-17 16:11 UTC, tlein commented on src/duckling/canvas/map-editor.component.ts
> +    private buildSelectionBoxAroundEntity(entity : Entity) : Graphics {
Privates need to be preceded with an underscore

2016-09-17 16:12 UTC, tlein requested changes

2016-09-17 19:49 UTC, jeffswenson requested changes
The Tool should be in charge of returning a display object. That allows us to re-use the mechanism for other things like
- The controls that allow you to resize an entity
- The controls that allow you to rotate an entity
- A selection box when we support multi-select
- The grid used to stamp out entities when we support tileing.

2016-09-28 00:48 UTC, jimmcnulty41 commented
Fixed issues from reviews

2016-09-28 00:58 UTC, tlein requested changes

2016-09-28 00:58 UTC, tlein commented on src/duckling/canvas/map-editor.component.ts
> +        this._toolDisplayObject = this.tool.getDisplayObject(this.scale);
You should call _redrawAllDisplayObjects when setting a new tool so that the different tool drawables will update when the tools are changed

2016-10-05 00:18 UTC, tlein approved these changes

2016-10-05 03:32 UTC, JeffSwenson commented on src/duckling/canvas/tools/entity-move-tool.ts
> +    private _buildSelectionBox(canvasZoom : number) : DisplayObject {
This function doesn't need to exist. It can just be getDisplayObject.

2016-10-05 03:32 UTC, JeffSwenson commented on src/duckling/canvas/tools/entity-creator-tool.ts
> +        let graphics : Graphics = null;
A lot of this code is duplicated in entity-move-tool.ts. You should extract it somehow.

2016-10-05 03:32 UTC, JeffSwenson commented on src/duckling/canvas/tools/entity-creator-tool.ts
> +        return this._buildSelectionBox(canvasZoom);
It seems weird that the tool is responsible for scaling itself. We scale entity elements for them. We should do the same for the tool.

2016-10-05 03:38 UTC, jeffswenson approved these changes

2016-10-05 04:09 UTC, merged