Preload images & show defaults for missing/loading assets and camera attribute
ild-games/duckling-legacy pull request #153
Opened 2016-10-02 02:49 UTC by tlein

Blocked by #152 (for angular2 material ui version bump)

Resolves #86 , #74 , #97 

![image](https://cloud.githubusercontent.com/assets/815242/19018288/f4446418-8820-11e6-8fdf-0fbb03ad2908.png)

2016-10-05 04:30 UTC, jeffswenson requested changes
If you have an invalid frame in an animation it gets skipped instead of showing the question mark draw-able.

2016-10-08 16:52 UTC, jeffswenson requested changes

2016-10-08 16:52 UTC, jeffswenson commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +            return drawer(entity, this._assets, needsLoading)
missing a ;

2016-10-08 16:52 UTC, jeffswenson commented on src/duckling/entitysystem/services/entity-box.service.ts
> +            let requiredAssets = this._requiredAssets.assetsForAttribute(key, entity);
This seems like an operation that should be handled by the asset service. You should wrap this up in a areAssetsReady(entity, component) call.

2016-10-08 16:52 UTC, jeffswenson commented on src/duckling/game/drawable/drawable-drawer.ts
> +function _missingAsset(assetService : AssetService) : Sprite {
I think this should be handled by the drawer service instead of the game drawable code.

2016-10-08 16:52 UTC, JeffSwenson commented on src/duckling/shell/shell.component.ts
> +    private _numImagesToLoad = 0;
This logic doesn't make sense to in the shell. The asset service should create a promise or an observable that fires once all requested assets have been loaded.

2016-10-08 16:52 UTC, JeffSwenson commented on src/duckling/util/path.service.ts
> +        return new Promise((resolve, reject) => {
I think you should use glob. https://www.npmjs.com/package/glob

2016-10-08 16:53 UTC, tlein commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +            return drawer(entity, this._assets, needsLoading)
fixed

2016-10-08 17:13 UTC, tlein commented on src/duckling/entitysystem/services/entity-box.service.ts
> +            let requiredAssets = this._requiredAssets.assetsForAttribute(key, entity);
fixed

2016-10-08 19:37 UTC, tlein commented on src/duckling/game/drawable/drawable-drawer.ts
> +function _missingAsset(assetService : AssetService) : Sprite {
fixed

2016-10-08 20:16 UTC, tlein commented on src/duckling/shell/shell.component.ts
> +    private _numImagesToLoad = 0;
fixed

2016-10-08 20:25 UTC, tlein commented on src/duckling/util/path.service.ts
> +        return new Promise((resolve, reject) => {
fixed

2016-10-08 22:51 UTC, JeffSwenson commented on src/duckling/util/path.service.ts
> +                    reject();
You should reject with the error.

2016-10-08 22:51 UTC, JeffSwenson commented on src/duckling/canvas/drawing/drawn-construct.ts
> +    function _setDisplayObjectPosition(displayObject : DisplayObject) {
Take this function out. V8 doesn't optimize t his behavior yet so it leads to an allocation every time.

2016-10-08 22:51 UTC, JeffSwenson commented on src/duckling/entitysystem/services/entity-box.service.ts
> +                box.position = this._entityPosition.getPosition(this._entitySystem.getKey(entity));
Don't Mutate the box! You should remove the copy in boxUnion and turn this into an immutable assign.

2016-10-08 22:51 UTC, tlein commented on src/duckling/util/path.service.ts
> +                    reject();
fixed

2016-10-08 22:53 UTC, tlein commented on src/duckling/canvas/drawing/drawn-construct.ts
> +    function _setDisplayObjectPosition(displayObject : DisplayObject) {
fixed

2016-10-08 23:18 UTC, jeffswenson approved these changes

2016-10-08 23:18 UTC, merged