Custom attribute ui
ild-games/duckling-legacy pull request #177
Opened 2016-10-27 04:11 UTC by tlein

Resolves #120

2016-10-27 04:12 UTC, tlein commented
Should we add an add button for arrays?

2016-11-23 18:55 UTC, JeffSwenson commented on src/duckling/controls/json.component.ts
> +    noop(element : any, i : number) {
I don't see where this is used.

2016-11-23 18:55 UTC, JeffSwenson commented on src/duckling/controls/section.component.scss
> +:host {
It seems like a bad idea to style the host. What makes this necessary?

2016-11-23 18:56 UTC, JeffSwenson commented on src/duckling/controls/section.component.ts
> +                [collapsible]="false"
You don't need to specify this. You made it the default.

2016-11-23 19:00 UTC, jeffswenson requested changes
Overall I think it looks really good.  Few nit picks.

2016-11-23 19:00 UTC, JeffSwenson commented on src/duckling/forms.scss
> +.form-label:not(:first-child) {
You could dry this up by nesting the first-child selector within form-label and overriding the padding there.

2016-11-23 19:00 UTC, JeffSwenson commented on src/duckling/controls/json.component.ts
> +            <dk-number-input
The intent would be more obvious if this was an ngSwitch

2016-11-26 18:39 UTC, tlein commented on src/duckling/controls/section.component.scss
> +:host {
Necessary for margin-top to take effect

2016-11-26 18:40 UTC, tlein commented on src/duckling/controls/section.component.ts
> +                [collapsible]="false"
flipped the default to true so now I do need to specify this

2016-11-26 18:43 UTC, tlein commented on src/duckling/controls/json.component.ts
> +    noop(element : any, i : number) {
removed, it was test code

2016-11-26 18:43 UTC, tlein commented on src/duckling/forms.scss
> +.form-label:not(:first-child) {
fixed

2016-11-26 19:06 UTC, tlein commented on src/duckling/controls/json.component.ts
> +            <dk-number-input
fixed

2016-11-26 20:58 UTC, jeffswenson approved these changes

2016-11-26 20:58 UTC, merged