Transform resize
ild-games/duckling-legacy pull request #178
Opened 2016-11-05 18:56 UTC by tlein

Resolves #90 

Engine breaking changes:
* ShapeDrawable circles are now ovals that have a radiusWidth and radiusHeight instead of just radius
* Collision attributes now have a scale property
* Rotation transforms are always applied before scaling transforms

2016-11-26 20:48 UTC, jeffswenson requested changes

2016-11-26 20:48 UTC, jeffswenson commented on src/duckling/canvas/tools/entity-move-tool.ts
> +    private _selectedCorner : Vector = null;
Why are you initializing these to null?

2016-11-26 20:48 UTC, jeffswenson commented on src/duckling/entitysystem/services/entity-eligible-resize.service.ts
> +export class EntityEligibleResizeService extends BaseAttributeService<AttributeEligibleForResize> {
I think this should be a function on the Resize service. It should return true if the entity has any implementations for resize.

2016-11-26 20:48 UTC, jeffswenson commented on src/duckling/game/collision/collision-eligible-for-resize.ts
> +export function collisionIsEligibleForResize() {
You can delete this if you listen to my other comment.

2016-11-26 20:48 UTC, JeffSwenson commented on src/duckling/canvas/tools/entity-move-tool.ts
> +        let selectedEntityKey = this._selectionService.selection.value.selectedEntity;
You should extract as much code as you can into stateless functions in another file. Consider naming it something like selection-box.ts

2016-11-26 20:48 UTC, JeffSwenson commented on src/duckling/game/collision/collision-size.ts
> +export function setCollisionSize(entity : Entity, newSize : Vector, assetService : AssetService) : CollisionAttribute {
This and the other set functions are good candidates for unit testing. They are complex and pure.

2016-11-27 01:01 UTC, tlein commented on src/duckling/entitysystem/services/entity-eligible-resize.service.ts
> +export class EntityEligibleResizeService extends BaseAttributeService<AttributeEligibleForResize> {
fixed

2016-11-27 01:01 UTC, tlein commented on src/duckling/game/collision/collision-eligible-for-resize.ts
> +export function collisionIsEligibleForResize() {
fixed

2017-02-13 03:10 UTC, closed without merging