Add layer support
ild-games/duckling-legacy pull request #179
Opened 2016-11-14 00:38 UTC by jimmcnulty41

In need of a rebase, but otherwise good

2016-11-26 18:36 UTC, jeffswenson requested changes

2016-11-26 18:36 UTC, jeffswenson commented on src/duckling/canvas/_toolbars/top-toolbar.component.ts
> +                private _viewContainer : ViewContainerRef,
You aren't using the MdDialog imports or private fields.

2016-11-26 18:36 UTC, jeffswenson commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +import {AssetService, RequiredAssetService} from '../../project';
You don't use RequiredAssetService.

2016-11-26 18:36 UTC, jeffswenson commented on src/duckling/canvas/map-editor.component.ts
> +                private _entityBoxService : EntityBoxService,
You aren't using _entityBoxService.

2016-11-26 18:36 UTC, JeffSwenson commented on src/duckling/controls/layer-dialog.component.scss
> +.show-hide-layer-button {
I don't think this needs to exist.

2016-11-26 18:36 UTC, JeffSwenson commented on src/duckling/controls/layer-dialog.component.ts
> +import {
This file doesn't belong in controls/. It should be in the same folder as the layers service.

2016-11-26 18:36 UTC, JeffSwenson commented on src/duckling/controls/layer-dialog.component.ts
> +        this.layers.sort((a, b) => {
This sorts 2 after 10.

2016-11-26 18:36 UTC, JeffSwenson commented on src/duckling/entitysystem/services/entity-layer.service.ts
> +    private _hiddenLayers : {[layerKey : string] : boolean} = {};
This should be stored in the redux store. That allows us to implement hot reloading in the future. You can also use that to make layer changes undo-able. Look at the selection service as an example.

2016-11-26 18:36 UTC, JeffSwenson commented on src/duckling/entitysystem/services/entity-selection.service.ts
> +    private _getVisibleEntities(entities : Array<Entity>) : Array<Entity> {
This should be a method on the layer service.

2016-11-30 02:37 UTC, jimmcnulty41 commented on src/duckling/canvas/_toolbars/top-toolbar.component.ts
> +                private _viewContainer : ViewContainerRef,
Cool

2016-11-30 02:37 UTC, jimmcnulty41 commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +import {AssetService, RequiredAssetService} from '../../project';
Cool

2016-11-30 02:38 UTC, jimmcnulty41 commented on src/duckling/canvas/map-editor.component.ts
> +                private _entityBoxService : EntityBoxService,
Cool

2016-11-30 02:38 UTC, jimmcnulty41 commented on src/duckling/controls/layer-dialog.component.scss
> +.show-hide-layer-button {
Cool

2016-11-30 02:38 UTC, jimmcnulty41 commented on src/duckling/controls/layer-dialog.component.ts
> +import {
Cool

2016-11-30 02:51 UTC, jimmcnulty41 commented on src/duckling/entitysystem/services/entity-selection.service.ts
> +    private _getVisibleEntities(entities : Array<Entity>) : Array<Entity> {
Cool

2016-11-30 03:50 UTC, tlein commented on src/duckling/entitysystem/services/entity-layer.service.ts
> +    private _hiddenLayers : {[layerKey : string] : boolean} = {};
cool

2016-11-30 04:01 UTC, tlein commented on src/duckling/controls/layer-dialog.component.ts
> +        this.layers.sort((a, b) => {
cool

2016-11-30 04:22 UTC, merged