Create custom attributes
ild-games/duckling-legacy pull request #212
Opened 2016-12-17 02:35 UTC by tlein

Part 1 of allowing the creation and usage of custom attributes with the editor.

This pull requests allows the creation of custom attribute templates from within the editor and saves them to a metadata file.

2016-12-21 04:58 UTC, tlein commented on src/duckling/project/project.ts
> +    name: string,
The type of this should be AttributeKey

2016-12-21 05:24 UTC, tlein commented on src/duckling/project/project.ts
> +    name: string,
Name should be "key" not "name"

2016-12-21 06:10 UTC, tlein commented on src/duckling/project/custom-attributes-depot.component.ts
> +                        (click)="selectAttribute(attribute)">
selectAttribute no longer exists, this needs to be removed

2016-12-22 00:32 UTC, tlein commented on src/duckling/project/project.ts
> +    name: string,
fixed both

2016-12-22 00:34 UTC, tlein commented on src/duckling/project/custom-attributes-depot.component.ts
> +                        (click)="selectAttribute(attribute)">
fixed

2016-12-22 00:46 UTC, tlein commented on src/duckling/project/json-schema.component.ts
> +    selector: "dk-json-schema",
Should rename to json-edit-schema.component

2017-01-08 22:16 UTC, jeffswenson requested changes

2017-01-08 22:16 UTC, JeffSwenson commented on src/duckling/project/custom-attributes-depot.component.ts
> +    styleUrls: ["./duckling/layout.css", "./duckling/project/custom-attributes-depot.component.css"],
The UX of this screen should be changed to resemble the splash screen.

2017-01-08 22:16 UTC, JeffSwenson commented on src/duckling/project/custom-attributes-depot.component.ts
> +                        Save
This doesn't actually save. You should change the name to Accept.

2017-01-08 22:16 UTC, JeffSwenson commented on src/duckling/project/custom-attributes-depot.component.ts
> +                    <div *ngIf="curAddingSchema !== undefined">
I don't think you should use curAddingSchema !== undefined as a state test. You should manage the state more explicitly.

2017-01-08 22:16 UTC, JeffSwenson commented on src/duckling/project/project.service.ts
> +            let json = await this._jsonLoader.getJsonFromPath(customAttribute);
Changing this to Promise.map allows you to load in parallel.

2017-01-08 22:16 UTC, JeffSwenson commented on src/duckling/project/json-schema.component.ts
> +                    <div *ngSwitchCase="JsonValueType.Number">
I think this could be dryer.

2017-01-21 05:57 UTC, tlein commented on src/duckling/project/custom-attributes-depot.component.ts
> +    styleUrls: ["./duckling/layout.css", "./duckling/project/custom-attributes-depot.component.css"],
fixed

2017-01-21 05:57 UTC, tlein commented on src/duckling/project/custom-attributes-depot.component.ts
> +                    <div *ngIf="curAddingSchema !== undefined">
fixed

2017-01-21 05:57 UTC, tlein commented on src/duckling/project/custom-attributes-depot.component.ts
> +                        Save
fixed

2017-01-21 05:58 UTC, tlein commented
Loading in custom attributes during map load needs to clear the undo/redo stack

2017-01-21 06:10 UTC, tlein commented on src/duckling/project/project.service.ts
> +            let json = await this._jsonLoader.getJsonFromPath(customAttribute);
fixed

2017-01-21 06:10 UTC, tlein commented on src/duckling/project/project.service.ts
> +            let json = await this._jsonLoader.getJsonFromPath(customAttribute);
fixed

2017-01-21 06:28 UTC, tlein commented
custom-attributes-depot should drop the depot from the name

2017-01-21 17:50 UTC, tlein commented on src/duckling/project/json-schema.component.ts
> +                    <div *ngSwitchCase="JsonValueType.Number">
fixed

2017-01-22 00:59 UTC, jeffswenson requested changes

2017-01-22 00:59 UTC, jeffswenson commented on src/duckling/project/project.service.ts
> +        Promise.all(attributePromises);
You need a return here.

2017-01-22 00:59 UTC, JeffSwenson commented on src/duckling/project/custom-attributes.component.ts
> +                            md-list-item
You don't need the md-list-item

2017-01-22 00:59 UTC, JeffSwenson commented on src/duckling/project/custom-attributes.component.scss
> +.container {
https://www.google.com/search?q=material+ui+dialogs&espv=2&biw=1893&bih=933&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjR94PLwtTRAhXkxFQKHYt-DbkQ_AUIBigB&dpr=1.25#imgrc=hGhlFtGv0HbhpM%3A

2017-01-22 00:59 UTC, JeffSwenson commented on src/duckling/project/json-schema.component.ts
> +    keys: string[],
I would changes this to one array and add key to the JsonSchemaValue.

2017-01-22 02:17 UTC, tlein commented on src/duckling/project/project.service.ts
> +        Promise.all(attributePromises);
fixed

2017-01-22 02:17 UTC, tlein commented on src/duckling/project/custom-attributes.component.ts
> +                            md-list-item
fixed

2017-01-22 02:25 UTC, tlein commented on src/duckling/project/custom-attributes.component.scss
> +.container {
Wrote up in #234

2017-01-22 02:35 UTC, jeffswenson approved these changes

2017-01-22 02:35 UTC, merged