Upgrade PixiJS, upgrade Material, lock down all package versions
ild-games/duckling-legacy pull request #248
Opened 2017-02-18 17:33 UTC by tlein

2017-02-18 18:29 UTC, JeffSwenson commented on src/duckling/project/asset.service.ts
> +        if (this._assetsToLoad.length > 0) {
You should queue all unloaded assets at the same time.

2017-02-18 20:13 UTC, JeffSwenson commented on src/index.html
> +      .mat-input-placeholder-wrapper::after {
You should remove this hack. Let's disable the inline input label.

2017-02-18 23:48 UTC, tlein commented on src/index.html
> +      .mat-input-placeholder-wrapper::after {
fixed

2017-02-19 00:38 UTC, tlein commented on src/duckling/project/asset.service.ts
> +        if (this._assetsToLoad.length > 0) {
fixed

2017-02-19 01:23 UTC, JeffSwenson commented on src/duckling/project/asset.service.ts
> +        if (assets.length > 0) {
This starts the loader even if the only asset loaded is a font.

2017-02-19 01:51 UTC, jeffswenson requested changes

2017-02-19 01:51 UTC, JeffSwenson commented on src/duckling/project/asset.service.ts
> +                if (!this._assetsToLoad[assetToLoad.asset.key]) {
This if is unnecessary.

2017-02-19 01:51 UTC, JeffSwenson commented on src/duckling/project/asset.service.ts
> +        if (loader.loading) {
You need a return here.

2017-02-19 01:51 UTC, JeffSwenson commented on src/duckling/project/asset.service.ts
> +        for (let assetToLoad of assets) {
I think you could modularize this function a little better.

2017-02-19 02:06 UTC, tlein commented on src/duckling/project/asset.service.ts
> +        for (let assetToLoad of assets) {
fixed

2017-02-19 02:07 UTC, tlein commented on src/duckling/project/asset.service.ts
> +                if (!this._assetsToLoad[assetToLoad.asset.key]) {
fixed

2017-02-19 02:07 UTC, tlein commented on src/duckling/project/asset.service.ts
> +        if (loader.loading) {
fixed

2017-02-19 02:07 UTC, tlein commented on src/duckling/project/asset.service.ts
> +        if (assets.length > 0) {
fixed

2017-02-19 02:18 UTC, merged