Springlings and paths
ild-games/duckling-legacy pull request #256
Opened 2017-02-21 03:01 UTC by tlein

2017-02-25 00:49 UTC, jimmcnulty41 commented on src/duckling/game/path/path-attribute.ts
> +    time: number
time doesn't tell us if it is one way or two way -- maybe timeToCycle, loopTime, etc.

2017-02-25 01:36 UTC, jimmcnulty41 requested changes

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/game/path/path-box.ts
> +    let boxDrawnConstruct = drawPathAttribute(entity);
As discussed, change to finding the min/max x/y values instead of doing the expensive pixi draw

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/game/path/path-drawer.ts
> +    if (!pathAttribute.isLoop) {
How about just if (pathAttribute.isLoop) { return drawLoopPath},
Then just return drawPath since we have already handled all the special cases

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/game/path/path-drawer.ts
> +    for (let i = 1; i < vertices.length - 1; i++) {
What if we draw all the lines, then just draw the loop indicator after the loop

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/game/path/path-drawer.ts
> +function _drawJoint(x : number, y: number) : DisplayObject {
change to take a position vector

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/game/path/path-drawer.ts
> +function _drawSegmentWithSquares(startVertex : Vector, endVertex : Vector, leftSquare : boolean, rightSquare : boolean) : DisplayObject {
I don't know if these more specific ones are actually helpful. I think calling like: for(verts) drawlines; drawSquare; drawSquare might be better

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/game/path/path.component.scss
> +
What's with the whitespace, man

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/math/vector.ts
> +export function vectorRotate(vector : Vector, radians : number, origin : Vector = {x: 0, y: 0}) : Vector {
Can you unit test this

2017-02-25 01:36 UTC, jimmcnulty41 commented on src/duckling/game/path/path.component.ts
> +        let newVertices = this.attribute.vertices.slice(0);
Can we do "let newVertices = [...this.attribute.vertices];"

2017-02-25 23:11 UTC, tlein commented on src/duckling/game/path/path-attribute.ts
> +    time: number
fixed

2017-02-25 23:39 UTC, tlein commented on src/duckling/game/path/path-box.ts
> +    let boxDrawnConstruct = drawPathAttribute(entity);
fixed

2017-02-25 23:42 UTC, tlein commented on src/duckling/game/path/path-drawer.ts
> +    if (!pathAttribute.isLoop) {
fixed

2017-02-25 23:43 UTC, tlein commented on src/duckling/game/path/path-drawer.ts
> +    for (let i = 1; i < vertices.length - 1; i++) {
that's what it currently is doing

2017-02-25 23:45 UTC, tlein commented on src/duckling/game/path/path-drawer.ts
> +function _drawSegmentWithSquares(startVertex : Vector, endVertex : Vector, leftSquare : boolean, rightSquare : boolean) : DisplayObject {
Not sure what you mean. Do you mean the "drawSegmentWithRightSquare" type of functions? I disagree about getting rid of them if so. I hate having 4 parameter values within my code with two random booleans at the end. It's not really clear what's happening.

2017-02-25 23:47 UTC, tlein commented on src/duckling/game/path/path-drawer.ts
> +function _drawJoint(x : number, y: number) : DisplayObject {
fixed

2017-02-25 23:48 UTC, tlein commented on src/duckling/game/path/path.component.scss
> +
fixed

2017-02-26 00:02 UTC, tlein commented on src/duckling/game/path/path.component.ts
> +        let newVertices = this.attribute.vertices.slice(0);
fixed

2017-02-26 16:31 UTC, tlein commented on src/duckling/math/vector.ts
> +export function vectorRotate(vector : Vector, radians : number, origin : Vector = {x: 0, y: 0}) : Vector {
fixed

2017-02-26 20:54 UTC, jimmcnulty41 commented on src/duckling/game/path/path-drawer.ts
> +function _drawSegmentWithSquares(startVertex : Vector, endVertex : Vector, leftSquare : boolean, rightSquare : boolean) : DisplayObject {
Nah, what I mean is that You wouldn't have any flavor of drawSegmentWithSquare. Instead, where you call those different functions, you would just call drawSegment, then call drawSquare

2017-02-26 20:54 UTC, jimmcnulty41 commented on src/duckling/game/path/path-drawer.ts
> +    for (let i = 1; i < vertices.length - 1; i++) {
except we're leaving out the first segment to draw later when we call drawFirstLoopSegment

2017-02-26 22:22 UTC, tlein commented on src/duckling/game/path/path-drawer.ts
> +    for (let i = 1; i < vertices.length - 1; i++) {
fixed

2017-02-26 22:22 UTC, tlein commented on src/duckling/game/path/path-drawer.ts
> +function _drawSegmentWithSquares(startVertex : Vector, endVertex : Vector, leftSquare : boolean, rightSquare : boolean) : DisplayObject {
fixed

2017-02-26 23:55 UTC, jimmcnulty41 commented
lgtm

2017-02-27 00:55 UTC, jimmcnulty41 approved these changes

2017-02-27 01:21 UTC, merged