Allow path gizmos to be hidden
ild-games/duckling-legacy pull request #292
Opened 2017-05-07 22:35 UTC by jimmcnulty41

Resolves #291 
Added an implementation for the layer service to path attributes.

`https://github.com/ild-games/duckling/issues/291`

Paths did not implement a function for the layer service. We now return a string "path-gizmos" for any entity that has a path attribute from a "getPathLayer" function which is bootstrapped into the entity-layer service

2017-05-07 22:54 UTC, tlein commented
We should refactor how the entity-drawer.service uses the entity-layer.service so that it doesn't draw specific attributes based on the layers hidden instead of the entire entity.

As it is, if you add a drawable to an entity with a path and hide the layer the drawable is on it will still render.

2017-05-07 23:41 UTC, jimmcnulty41 commented
As in the drawable still renders?

2017-05-07 23:42 UTC, tlein commented
Yes, the drawable on the entity that is on the hidden layer will still render if that entity also has a path attribute.

2017-05-13 05:10 UTC, tlein requested changes

2017-05-13 05:10 UTC, tlein commented on src/duckling/entitysystem/services/entity-layer.service.ts
> +        // an entity is visible if any of its attributes are on visible layers
this comment isn't necessary

2017-05-13 05:10 UTC, tlein commented on src/duckling/entitysystem/services/entity-layer.service.ts
> +    isEntityAttributeVisible(entity: Entity, attributeKey: string){
add a space between the ){

2017-05-13 05:18 UTC, merged