Primitive drawer
ild-games/duckling-legacy pull request #293
Opened 2017-05-14 05:06 UTC by tlein

2017-05-16 03:38 UTC, tlein commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +    paint?(attribute : T, position : Vector, graphics : Graphics) : void,
This is weird syntax: 

`paint? : (attribute : T, position : Vector, graphics : Graphics) => void`

2017-05-18 00:46 UTC, tlein commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +        graphics.clear();
This clear should only be in the map-editor when the painted cache is killed

2017-05-18 01:22 UTC, JeffSwenson commented
Instead of forking the drawing infrastructure you should create a Painter DrawnConstruct.

2017-05-18 01:40 UTC, JeffSwenson commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +        let newCache : EntityCache = {};
I think we should have the cache held by the MapDrawer and this should expose a InvalidateDrawableCache observer that fires an event when something causes the drawable cache to be stale.

2017-05-27 02:57 UTC, jeffswenson requested changes

2017-05-27 02:57 UTC, JeffSwenson commented on src/duckling/canvas/map-editor.component.ts
> +        if (this._drawableCache[BACKGROUND_CACHE_KEY].dirty) {
There should be a way to dry this up.

2017-05-27 02:57 UTC, JeffSwenson commented on src/duckling/canvas/map-editor.component.ts
> +        if (this._drawableCache[BACKGROUND_CACHE_KEY].dirty) {
I think DrawableCache should be a class. The constructor should take a function that is called to rebuild the cache. You ould transform things like:

this._markeCacheDirty(cacheKey) to this.cache.cacheKey.dirty = true;

2017-05-27 02:57 UTC, JeffSwenson commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +        if (drawer && drawer) {
drawer && drawer

2017-05-27 02:57 UTC, JeffSwenson commented on src/duckling/canvas/drawing/drawn-construct.ts
> +import {Container, DisplayObject, Point, Graphics} from 'pixi.js';
As we discussed offline
I think DrawnConstruct should be a polymorphic interface with drawable?, paint?, and layer:string properties.

The loop used to draw entites should be replaced with
for (entity) for (attribute) constructs.push(getConstruct(attribute))
constructs.sort(construct.layer)

When drawing, you should create a new graphics object for each layer.

2017-05-29 14:26 UTC, tlein commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +        if (drawer && drawer) {
fixed

2017-05-29 14:26 UTC, tlein commented on src/duckling/canvas/drawing/drawn-construct.ts
> +import {Container, DisplayObject, Point, Graphics} from 'pixi.js';
fixed, though we need to look at performance because it's slower to rebuild the display object snow

2017-05-29 14:27 UTC, tlein commented on src/duckling/canvas/drawing/entity-drawer.service.ts
> +        let newCache : EntityCache = {};
fixed

2017-06-15 00:18 UTC, jeffswenson approved these changes

2017-06-15 00:18 UTC, jeffswenson commented on src/duckling/canvas/drawing/drawn-construct.ts
> +        if (this.transformProperties.rotation) {
this optimization results in a problem if you change rotation from a non-zero value to a zero value.

2017-06-15 00:22 UTC, merged